### ISSUE TITLE
Crash with Thermal Dynamics

### ISSUE THREAD

**Issue by poisax** [SmileycorpMC/Cosmetic-Wood#1]
I'm really not sure how to describe the issue, other than that it occurs on startup.
https://pastebin.com/0UBb2dkS

**Comment by SmileycorpMC** [comment]
It seems to be an issue with how Thermal Dynamics creates it's covers.
I'll have a look into if this crash can be solved.

**Comment by SmileycorpMC** [comment]
fixed as of version 1.1.1.
